apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: latest
  name: techtrends
  namespace: sandbox # {{ .Values.namespace.name }}
spec:
  replicas: 1 # {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
      tag: latest
#  strategy:
#    rollingUpdate:
#      maxSurge: 25%
#      maxUnavailable: 25%
#    type: RollingUpdate
  template:
#    metadata:
#      labels:
#        app: techtrends
#        tag: latest
    spec:
      containers:
      - image: techtrends:latest # {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent # {{ .Values.image.pullPolicy }}
        name: techtrends

        resources:
          requests:
            cpu: 250m
            memory: 64Mi

          limits:
            cpu: 500m
            memory: 128Mi

        ports:
          - containerPort: 3111
            protocol: TCP

        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111

        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111

        # {{ toYaml .Values.resources | indent 12 }}
