apiVersion: v1
kind: Service

metadata:
  labels:
    app: techtrends
    tag: latest

  name: techtrends
  namespace: sandbox # {{ .Values.namespace.name }}

spec:
  ports:
  - port: 4111 # {{ .Values.service.port }}
    protocol: TCP
    targetPort: 3111 # {{ .Values.service.port }}

  selector:
    app: techtrends
    tag: latest

  type: ClusterIP # {{ .Values.service.type }}
