# Ref:
#  1. https://docs.docker.com/build/ci/github-actions/
#  2. https://github.com/marketplace/actions/build-and-push-docker-images
#

##  Named of the workflow.
name: "TechTrends - Package with Docker"

## Set the trigger policy.
## In this case, the workflow executes on a `push` event,
## or when a new commit is pushed to the repository
on:
  push:
    branches:
      - main

## List the steps to be executed by the workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:project"
          push: true
          tags: ${{ secrets.DOCKER_USER }}/techtrends:latest
